// PerformanceMonitor.tsx
'use client';
import React from 'react';
import usePerformanceMonitor from '../../hooks/usePerformanceMonitor';

export default function PerformanceMonitor() {
  const { fps = 0, memory = 0, render = 0 } = usePerformanceMonitor() as any;
  return (
    <div style={{ display: 'flex', gap: 12, alignItems: 'center', padding: 8 }}>
      <div style={{ fontVariantNumeric: 'tabular-nums' }}>
        FPS: <strong>{fps}</strong>
      </div>
      <div style={{ fontVariantNumeric: 'tabular-nums' }}>
        Heap MB: <strong>{memory}</strong>
      </div>
      <div style={{ fontVariantNumeric: 'tabular-nums' }}>
        Render ms: <strong>{render}</strong>
      </div>
    </div>
  );
}

// PerformanceMonitor.vue
﻿<template>
  <div style="display: flex; gap: 12px; padding: 8px; margin-bottom: 24px;">
    <div><strong>FPS:</strong> {{ fps }}</div>
    <div><strong>Memory:</strong> {{ memory }} MB</div>
    <div><strong>Render:</strong> {{ render }} ms</div>
  </div>
</template>

<script setup lang="ts">
import usePerformanceMonitor from "../../composables/usePerformanceMonitor";

const { fps, memory, render } = usePerformanceMonitor();
</script>
